import "./globals.css";
import Header from "@/app/components/Header.js";
import { Mulish } from "next/font/google";
import Footer from "@/app/components/Footer.js";

// If loading a variable font, you don't need to specify the font weight
const mulish = Mulish({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "YFLIX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
